export const PLACEHOLDER_ONLY_SCOPE_ID = 'placeholder-only'

export const STARTER_QUESTION_BANK_SCOPES = [
  {
    id: 'class-6-mathematics-arithmetic-integers',
    label: 'Class 6 Mathematics - Arithmetic: Integers',
    productId: 'AR-QUESTION-PRO',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    description: 'Small original starter bank for basic integer concepts and operations.',
  },
]

export const STARTER_QUESTION_BANK = [
  {
    id: 'c6-math-int-001',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Easy',
    questionType: 'Short answer',
    marks: 1,
    question: 'Write the integer that represents a loss of 8 points.',
    answer: '-8',
    solution: 'A loss is represented by a negative integer, so the integer is -8.',
  },
  {
    id: 'c6-math-int-002',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Easy',
    questionType: 'Short answer',
    marks: 1,
    question: 'Which integer is greater: -3 or -7?',
    answer: '-3',
    solution: '-3 is closer to zero on the number line, so it is greater than -7.',
  },
  {
    id: 'c6-math-int-003',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Easy',
    questionType: 'Short answer',
    marks: 1,
    question: 'Find the sum: -4 + 9.',
    answer: '5',
    solution: 'Moving 9 steps right from -4 gives 5.',
  },
  {
    id: 'c6-math-int-004',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Easy',
    questionType: 'Short answer',
    marks: 1,
    question: 'Find the value of 6 + (-2).',
    answer: '4',
    solution: 'Adding -2 means moving 2 steps left from 6, which gives 4.',
  },
  {
    id: 'c6-math-int-005',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Easy',
    questionType: 'Short answer',
    marks: 1,
    question: 'Arrange these integers in ascending order: 2, -5, 0, -1.',
    answer: '-5, -1, 0, 2',
    solution: 'Ascending order goes from the smallest integer to the greatest integer.',
  },
  {
    id: 'c6-math-int-006',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Medium',
    questionType: 'Short answer',
    marks: 2,
    question: 'Find the value of -12 + 5.',
    answer: '-7',
    solution: 'Starting at -12 and moving 5 steps right gives -7.',
  },
  {
    id: 'c6-math-int-007',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Medium',
    questionType: 'Short answer',
    marks: 2,
    question: 'Find the value of 7 - 11.',
    answer: '-4',
    solution: 'Subtracting 11 from 7 gives 7 + (-11), which is -4.',
  },
  {
    id: 'c6-math-int-008',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Medium',
    questionType: 'Short answer',
    marks: 2,
    question: 'A temperature changes from -2 degrees to 5 degrees. By how many degrees did it rise?',
    answer: '7 degrees',
    solution: 'The change is 5 - (-2) = 7 degrees.',
  },
  {
    id: 'c6-math-int-009',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Medium',
    questionType: 'Short answer',
    marks: 2,
    question: 'Find the value of -6 - 4.',
    answer: '-10',
    solution: 'Subtracting 4 means moving 4 steps left from -6, which gives -10.',
  },
  {
    id: 'c6-math-int-010',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Medium',
    questionType: 'Short answer',
    marks: 2,
    question: 'Write two integers whose sum is -3.',
    answer: 'Sample answer: -5 and 2',
    solution: 'Many answers are possible. For example, -5 + 2 = -3.',
  },
  {
    id: 'c6-math-int-011',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Medium',
    questionType: 'Short answer',
    marks: 2,
    question: 'Find the value of 15 + (-9) + (-4).',
    answer: '2',
    solution: 'First combine the negative integers: -9 + (-4) = -13. Then 15 + (-13) = 2.',
  },
  {
    id: 'c6-math-int-012',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Hard',
    questionType: 'Short answer',
    marks: 3,
    question: 'A diver is 6 metres below sea level and rises 4 metres. Write the final position as an integer.',
    answer: '-2 metres',
    solution: 'The starting position is -6. Rising 4 metres gives -6 + 4 = -2.',
  },
  {
    id: 'c6-math-int-013',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Hard',
    questionType: 'Short answer',
    marks: 3,
    question: 'Find the missing integer: -8 + ___ = 3.',
    answer: '11',
    solution: 'The missing number is 3 - (-8), which is 11.',
  },
  {
    id: 'c6-math-int-014',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Hard',
    questionType: 'Short answer',
    marks: 3,
    question: 'A team gains 12 points in one round and loses 17 points in the next round. What is the net score?',
    answer: '-5 points',
    solution: 'The net score is 12 + (-17) = -5.',
  },
  {
    id: 'c6-math-int-015',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Hard',
    questionType: 'Short answer',
    marks: 3,
    question: 'Find the value of -3 - (-8) + 2.',
    answer: '7',
    solution: '-3 - (-8) is the same as -3 + 8 = 5. Then 5 + 2 = 7.',
  },
  {
    id: 'c6-math-int-016',
    productId: 'AR-QUESTION-PRO',
    scopeId: 'class-6-mathematics-arithmetic-integers',
    grade: 'Class 6',
    subject: 'Mathematics',
    board: 'CBSE or General',
    chapter: 'Arithmetic',
    topic: 'Integers',
    difficulty: 'Hard',
    questionType: 'Short answer',
    marks: 3,
    question: 'Create a number line movement for the expression -2 + 6 - 9 and find the final integer.',
    answer: '-5',
    solution: 'Start at -2, move 6 steps right to 4, then move 9 steps left to -5.',
  },
]
